# Generated by Django 2.1.5 on 2019-02-15 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_place_type', models.CharField(max_length=255, verbose_name='Tipo de Lougradoudo')),
                ('public_place_name', models.CharField(max_length=255, verbose_name='Lougradouro')),
                ('number', models.CharField(max_length=255, verbose_name='Número')),
                ('sector', models.CharField(max_length=255, verbose_name='Setor/Bairro')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Cliente')),
                ('contact', models.CharField(max_length=255, verbose_name='Contato')),
                ('contact_sector', models.CharField(max_length=255, verbose_name='Setor')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('national_legal_number', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('state_legal_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscrição Estadual')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_equipment', models.CharField(max_length=255, verbose_name='Equipamento')),
                ('manufacture', models.CharField(max_length=255, verbose_name='Fabricante')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Série do Equipamento')),
                ('issue', models.CharField(max_length=255, verbose_name='Defeito')),
                ('type_of_invoice', models.CharField(choices=[('Contrato', 'Contrato'), ('Fatura', 'Fatura'), ('Garantia', 'Garantia'), ('Instalação', 'Instalação')], max_length=255, verbose_name='Tipo da Ordem de Serviço')),
                ('invoice_description', models.TextField(blank=True, verbose_name='Descrição do Serviço')),
                ('total_value', models.FloatField(blank=True, null=True, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Aberto', 'Em Aberto'), ('Paga', 'Paga')], max_length=255, verbose_name='Status da Ordem de Serviço')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Equipment', verbose_name='Equipamento')),
                ('service_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Address', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_supply', models.CharField(choices=[('Hora Trabalhada', 'Hora Trabalhada'), ('Outros', 'Outros')], max_length=255, verbose_name='Unidade de Medida')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Materiais/Serviços')),
                ('amount', models.FloatField(verbose_name='Quantidade')),
                ('unit', models.CharField(choices=[('Kilômetro(s)', 'Kilômetro(s)'), ('Kilograma(s)', 'Kilograma(s)'), ('Unidade(s)', 'Unidade(s)'), ('Hora(s)', 'Hora(s)')], max_length=255, verbose_name='Unidade de Medida')),
                ('value', models.FloatField(verbose_name='Valor Unitário')),
                ('invoice_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.Invoice', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Material/Serviço',
                'verbose_name_plural': 'Materiais/Serviços',
                'db_table': 'supply',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplies',
            field=models.ManyToManyField(blank=True, to='invoices.Supply', verbose_name='Serviços/Materiais'),
        ),
    ]
