# Generated by Django 2.1.5 on 2019-02-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trading_name',
            field=models.CharField(default=0, max_length=255, verbose_name='Nome Fantasia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Aberto', 'Em Aberto'), ('Paga', 'Paga')], default='Pendente', max_length=255, verbose_name='Status da Ordem de Serviço'),
        ),
    ]
