# Generated by Django 2.1.5 on 2019-02-19 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20190215_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_legal_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Telefone'),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='supplies',
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplies',
            field=models.TextField(blank=True, verbose_name='Serviços/Materiais'),
        ),
    ]
