# Generated by Django 2.1.5 on 2019-02-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20190218_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='type_of_supply',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplies',
            field=models.TextField(blank=True, verbose_name='Materiais/Serviços'),
        ),
    ]
