# Generated by Django 2.1.5 on 2019-02-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20190219_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='supplies',
        ),
    ]
