# Generated by Django 2.1.5 on 2019-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_supplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplies',
            field=models.ManyToManyField(blank=True, to='invoices.Supply', verbose_name='Materiais/Serviços'),
        ),
    ]
