# Generated by Django 2.1.5 on 2019-02-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_supplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='invoice_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice', verbose_name='Ordem de Serviço'),
        ),
    ]
