# Generated by Django 2.1.5 on 2019-02-21 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20190221_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefone'),
        ),
    ]
